### PR TITLE
Lint Python Code

### PR DESCRIPTION
**Pull request by ivan-c**
- Run `flake8` and [`black`](https://github.com/psf/black) to lint python code
- Run `flake8` and `black` as part of CI

### CODE REVIEW

**Comment by ivan-c** [comment]
@pbugni I used `black` out of the box, but I'm fine configuring it as you prefer, or not using it at all

**Review by achen2401 — APPROVED** [review]

**Comment by ivan-c** [comment]
@pbugni
`flake8` is complaining about [this import](https://github.com/uwcirg/cosri-patientsearch/pull/111/files#annotation_2494427829), it should be fine to remove, right?

**Comment by ivan-c** [comment]
> @pbugni `flake8` is complaining about [this import](https://github.com/uwcirg/cosri-patientsearch/pull/111/files#annotation_2494427829), it should be fine to remove, right?

Fixed!

**Review by pbugni — APPROVED** [review]
💯 
Thank you - this is wonderful

**Pull request merged**
