### PR TITLE
Adding hook and config for new resource annotations.

### PR DESCRIPTION
**Pull request by pbugni**
NB, HAPI won't take a null or empty string for the extension's valueDateTime - using an arbitrary 50 year out date, as we sort by oldest first.

This "femr" feature is only enabled with `NEW_PATIENT_EXTENSIONS` environment variable defined.  See related PR https://github.com/uwcirg/isacc-environments/pull/20

Example:

```
NEW_PATIENT_EXTENSIONS: '[{"url": "http://isacc.app/time-of-last-unfollowedup-message", "valueDateTime": "2073-01-01T00:00:00.0+00:00"}]'
```

### CODE REVIEW

**Review by achen2401 — APPROVED** [review]
thanks, @pbugni   This looks to work on the **new** patient I added:
Screen Shot 2023-05-10 at 3 22 04 PM

There are existing patient records in both shared dev and eval systems.  And if I understand the code change here correctly, those won't be modified?  Just need to keep that in mind when we test.

**Comment by pbugni** [comment]
> thanks, @pbugni This looks to work on the **new** patient I added: Screen Shot 2023-05-10 at 3 22 04 PM
> 
> There are existing patient records in both shared dev and eval systems. And if I understand the code change here correctly, those won't be modified? Just need to keep that in mind when we test.

that is correct @achen2401 - i could probably script that if we need it, however.

**Comment by pbugni** [comment]
> There are existing patient records in both shared dev and eval systems. And if I understand the code change here correctly, those won't be modified? Just need to keep that in mind when we test.

that is correct @achen2401 - i could probably script that if we need it, however.

**Comment by pbugni** [comment]
> There are existing patient records in both shared dev and eval systems. And if I understand the code change here correctly, those won't be modified? Just need to keep that in mind when we test.

that is correct @achen2401 - i could probably script that reasonably easy, if we need it?

**Pull request merged**
