### PR TITLE
Include configuration value `need_patient_banner` in launch params

### PR DESCRIPTION
**Pull request by pbugni**
Pass `need_patient_banner` to fEMR launch apps.

done: Add config var for an environment to control `need_patient_banner` setting.
done: Pass `need_patient_banner` adjacent to other launch query string parameters.

### CODE REVIEW

**Review by achen2401 — APPROVED** [review]

**Review by mcjustin — APPROVED** [review]

**Comment by pbugni** [comment]
@achen2401 this looked like it slipped through the cracks, but when I rebase with develop to sort out the merge conflict, I see the changes have already been added to the work you did WRT `getAppLaunchURL`?  I think we can safely close this PR, unless I'm missing something?  Thanks.

**Comment by achen2401** [comment]
Thanks @pbugni .  Yeah, I believe we can close this PR.

**Comment by achen2401** [comment]
@pbugni Please ignore my previous comment. I realize that we should merge this because we still need config var for an environment to control `need_patient_banner` setting.  We probably should merge open PR's related to this:
For COSRI environment: https://github.com/uwcirg/cosri-environments/pull/83
For DCW environment: https://github.com/uwcirg/dcw-environments/pull/27

I did resolve the conflict related to `PatientListTable.js` that was blocking the merge of this.

**Comment by pbugni** [comment]
Thank you @achen2401

**Pull request merged**
